service: smart-property-search

provider:
  name: aws
  timeout: 120
  runtime: python3.6
  region: ${env:AWS_REGION}
  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    GOOGLE_MAPS_KEY: ${env:GOOGLE_MAPS_KEY}
    WSAPIKEY: ${env:WSAPIKEY}

functions:
  search:
    module: src
    handler: handler.search
    include:
      - src/**
    events:
      - http:
          path: search
          method: post
          request:
            schema:
              application/json: ${file(search_schema.json)}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
