# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainAgencyServiceV2ModelAgencyProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agency_photos': 'list[DomainAgencyServiceV2ModelAgencyPhoto]',
        'profile_website': 'str',
        'agency_banner': 'str',
        'agency_website': 'str',
        'agency_logo_standard': 'str',
        'agency_logo_small': 'str',
        'logo_colour': 'str',
        'primary_agency_colour': 'str',
        'background_colour': 'str',
        'map_latitude': 'str',
        'map_longitude': 'str',
        'map_certainty': 'int',
        'agency_video_url': 'str',
        'agency_description': 'str',
        'agency_description_cre': 'str',
        'cre_profile_website': 'str',
        'agency_cre_banner': 'str',
        'agency_cre_website': 'str',
        'agency_cre_logo_standard': 'str',
        'number_for_sale': 'int',
        'number_for_rent': 'int',
        'number_for_sale_commercial': 'int',
        'number_for_rent_commercial': 'int',
        'cre_agency_video_url': 'str'
    }

    attribute_map = {
        'agency_photos': 'agencyPhotos',
        'profile_website': 'profileWebsite',
        'agency_banner': 'agencyBanner',
        'agency_website': 'agencyWebsite',
        'agency_logo_standard': 'agencyLogoStandard',
        'agency_logo_small': 'agencyLogoSmall',
        'logo_colour': 'logoColour',
        'primary_agency_colour': 'primaryAgencyColour',
        'background_colour': 'backgroundColour',
        'map_latitude': 'mapLatitude',
        'map_longitude': 'mapLongitude',
        'map_certainty': 'mapCertainty',
        'agency_video_url': 'agencyVideoUrl',
        'agency_description': 'agencyDescription',
        'agency_description_cre': 'agencyDescriptionCre',
        'cre_profile_website': 'creProfileWebsite',
        'agency_cre_banner': 'agencyCreBanner',
        'agency_cre_website': 'agencyCreWebsite',
        'agency_cre_logo_standard': 'agencyCreLogoStandard',
        'number_for_sale': 'numberForSale',
        'number_for_rent': 'numberForRent',
        'number_for_sale_commercial': 'numberForSaleCommercial',
        'number_for_rent_commercial': 'numberForRentCommercial',
        'cre_agency_video_url': 'creAgencyVideoUrl'
    }

    def __init__(self, agency_photos=None, profile_website=None, agency_banner=None, agency_website=None, agency_logo_standard=None, agency_logo_small=None, logo_colour=None, primary_agency_colour=None, background_colour=None, map_latitude=None, map_longitude=None, map_certainty=None, agency_video_url=None, agency_description=None, agency_description_cre=None, cre_profile_website=None, agency_cre_banner=None, agency_cre_website=None, agency_cre_logo_standard=None, number_for_sale=None, number_for_rent=None, number_for_sale_commercial=None, number_for_rent_commercial=None, cre_agency_video_url=None):  # noqa: E501
        """DomainAgencyServiceV2ModelAgencyProfile - a model defined in Swagger"""  # noqa: E501

        self._agency_photos = None
        self._profile_website = None
        self._agency_banner = None
        self._agency_website = None
        self._agency_logo_standard = None
        self._agency_logo_small = None
        self._logo_colour = None
        self._primary_agency_colour = None
        self._background_colour = None
        self._map_latitude = None
        self._map_longitude = None
        self._map_certainty = None
        self._agency_video_url = None
        self._agency_description = None
        self._agency_description_cre = None
        self._cre_profile_website = None
        self._agency_cre_banner = None
        self._agency_cre_website = None
        self._agency_cre_logo_standard = None
        self._number_for_sale = None
        self._number_for_rent = None
        self._number_for_sale_commercial = None
        self._number_for_rent_commercial = None
        self._cre_agency_video_url = None
        self.discriminator = None

        if agency_photos is not None:
            self.agency_photos = agency_photos
        if profile_website is not None:
            self.profile_website = profile_website
        if agency_banner is not None:
            self.agency_banner = agency_banner
        if agency_website is not None:
            self.agency_website = agency_website
        if agency_logo_standard is not None:
            self.agency_logo_standard = agency_logo_standard
        if agency_logo_small is not None:
            self.agency_logo_small = agency_logo_small
        if logo_colour is not None:
            self.logo_colour = logo_colour
        if primary_agency_colour is not None:
            self.primary_agency_colour = primary_agency_colour
        if background_colour is not None:
            self.background_colour = background_colour
        if map_latitude is not None:
            self.map_latitude = map_latitude
        if map_longitude is not None:
            self.map_longitude = map_longitude
        if map_certainty is not None:
            self.map_certainty = map_certainty
        if agency_video_url is not None:
            self.agency_video_url = agency_video_url
        if agency_description is not None:
            self.agency_description = agency_description
        if agency_description_cre is not None:
            self.agency_description_cre = agency_description_cre
        if cre_profile_website is not None:
            self.cre_profile_website = cre_profile_website
        if agency_cre_banner is not None:
            self.agency_cre_banner = agency_cre_banner
        if agency_cre_website is not None:
            self.agency_cre_website = agency_cre_website
        if agency_cre_logo_standard is not None:
            self.agency_cre_logo_standard = agency_cre_logo_standard
        if number_for_sale is not None:
            self.number_for_sale = number_for_sale
        if number_for_rent is not None:
            self.number_for_rent = number_for_rent
        if number_for_sale_commercial is not None:
            self.number_for_sale_commercial = number_for_sale_commercial
        if number_for_rent_commercial is not None:
            self.number_for_rent_commercial = number_for_rent_commercial
        if cre_agency_video_url is not None:
            self.cre_agency_video_url = cre_agency_video_url

    @property
    def agency_photos(self):
        """Gets the agency_photos of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_photos of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: list[DomainAgencyServiceV2ModelAgencyPhoto]
        """
        return self._agency_photos

    @agency_photos.setter
    def agency_photos(self, agency_photos):
        """Sets the agency_photos of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_photos: The agency_photos of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: list[DomainAgencyServiceV2ModelAgencyPhoto]
        """

        self._agency_photos = agency_photos

    @property
    def profile_website(self):
        """Gets the profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._profile_website

    @profile_website.setter
    def profile_website(self, profile_website):
        """Sets the profile_website of this DomainAgencyServiceV2ModelAgencyProfile.


        :param profile_website: The profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._profile_website = profile_website

    @property
    def agency_banner(self):
        """Gets the agency_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_banner

    @agency_banner.setter
    def agency_banner(self, agency_banner):
        """Sets the agency_banner of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_banner: The agency_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_banner = agency_banner

    @property
    def agency_website(self):
        """Gets the agency_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_website

    @agency_website.setter
    def agency_website(self, agency_website):
        """Sets the agency_website of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_website: The agency_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_website = agency_website

    @property
    def agency_logo_standard(self):
        """Gets the agency_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_logo_standard

    @agency_logo_standard.setter
    def agency_logo_standard(self, agency_logo_standard):
        """Sets the agency_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_logo_standard: The agency_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_logo_standard = agency_logo_standard

    @property
    def agency_logo_small(self):
        """Gets the agency_logo_small of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_logo_small of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_logo_small

    @agency_logo_small.setter
    def agency_logo_small(self, agency_logo_small):
        """Sets the agency_logo_small of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_logo_small: The agency_logo_small of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_logo_small = agency_logo_small

    @property
    def logo_colour(self):
        """Gets the logo_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The logo_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._logo_colour

    @logo_colour.setter
    def logo_colour(self, logo_colour):
        """Sets the logo_colour of this DomainAgencyServiceV2ModelAgencyProfile.


        :param logo_colour: The logo_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._logo_colour = logo_colour

    @property
    def primary_agency_colour(self):
        """Gets the primary_agency_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The primary_agency_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._primary_agency_colour

    @primary_agency_colour.setter
    def primary_agency_colour(self, primary_agency_colour):
        """Sets the primary_agency_colour of this DomainAgencyServiceV2ModelAgencyProfile.


        :param primary_agency_colour: The primary_agency_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._primary_agency_colour = primary_agency_colour

    @property
    def background_colour(self):
        """Gets the background_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The background_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._background_colour

    @background_colour.setter
    def background_colour(self, background_colour):
        """Sets the background_colour of this DomainAgencyServiceV2ModelAgencyProfile.


        :param background_colour: The background_colour of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._background_colour = background_colour

    @property
    def map_latitude(self):
        """Gets the map_latitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The map_latitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._map_latitude

    @map_latitude.setter
    def map_latitude(self, map_latitude):
        """Sets the map_latitude of this DomainAgencyServiceV2ModelAgencyProfile.


        :param map_latitude: The map_latitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._map_latitude = map_latitude

    @property
    def map_longitude(self):
        """Gets the map_longitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The map_longitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._map_longitude

    @map_longitude.setter
    def map_longitude(self, map_longitude):
        """Sets the map_longitude of this DomainAgencyServiceV2ModelAgencyProfile.


        :param map_longitude: The map_longitude of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._map_longitude = map_longitude

    @property
    def map_certainty(self):
        """Gets the map_certainty of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The map_certainty of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: int
        """
        return self._map_certainty

    @map_certainty.setter
    def map_certainty(self, map_certainty):
        """Sets the map_certainty of this DomainAgencyServiceV2ModelAgencyProfile.


        :param map_certainty: The map_certainty of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: int
        """

        self._map_certainty = map_certainty

    @property
    def agency_video_url(self):
        """Gets the agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_video_url

    @agency_video_url.setter
    def agency_video_url(self, agency_video_url):
        """Sets the agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_video_url: The agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_video_url = agency_video_url

    @property
    def agency_description(self):
        """Gets the agency_description of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_description of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_description

    @agency_description.setter
    def agency_description(self, agency_description):
        """Sets the agency_description of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_description: The agency_description of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_description = agency_description

    @property
    def agency_description_cre(self):
        """Gets the agency_description_cre of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_description_cre of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_description_cre

    @agency_description_cre.setter
    def agency_description_cre(self, agency_description_cre):
        """Sets the agency_description_cre of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_description_cre: The agency_description_cre of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_description_cre = agency_description_cre

    @property
    def cre_profile_website(self):
        """Gets the cre_profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The cre_profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._cre_profile_website

    @cre_profile_website.setter
    def cre_profile_website(self, cre_profile_website):
        """Sets the cre_profile_website of this DomainAgencyServiceV2ModelAgencyProfile.


        :param cre_profile_website: The cre_profile_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._cre_profile_website = cre_profile_website

    @property
    def agency_cre_banner(self):
        """Gets the agency_cre_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_cre_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_cre_banner

    @agency_cre_banner.setter
    def agency_cre_banner(self, agency_cre_banner):
        """Sets the agency_cre_banner of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_cre_banner: The agency_cre_banner of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_cre_banner = agency_cre_banner

    @property
    def agency_cre_website(self):
        """Gets the agency_cre_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_cre_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_cre_website

    @agency_cre_website.setter
    def agency_cre_website(self, agency_cre_website):
        """Sets the agency_cre_website of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_cre_website: The agency_cre_website of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_cre_website = agency_cre_website

    @property
    def agency_cre_logo_standard(self):
        """Gets the agency_cre_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The agency_cre_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._agency_cre_logo_standard

    @agency_cre_logo_standard.setter
    def agency_cre_logo_standard(self, agency_cre_logo_standard):
        """Sets the agency_cre_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.


        :param agency_cre_logo_standard: The agency_cre_logo_standard of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._agency_cre_logo_standard = agency_cre_logo_standard

    @property
    def number_for_sale(self):
        """Gets the number_for_sale of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The number_for_sale of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: int
        """
        return self._number_for_sale

    @number_for_sale.setter
    def number_for_sale(self, number_for_sale):
        """Sets the number_for_sale of this DomainAgencyServiceV2ModelAgencyProfile.


        :param number_for_sale: The number_for_sale of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: int
        """

        self._number_for_sale = number_for_sale

    @property
    def number_for_rent(self):
        """Gets the number_for_rent of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The number_for_rent of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: int
        """
        return self._number_for_rent

    @number_for_rent.setter
    def number_for_rent(self, number_for_rent):
        """Sets the number_for_rent of this DomainAgencyServiceV2ModelAgencyProfile.


        :param number_for_rent: The number_for_rent of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: int
        """

        self._number_for_rent = number_for_rent

    @property
    def number_for_sale_commercial(self):
        """Gets the number_for_sale_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The number_for_sale_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: int
        """
        return self._number_for_sale_commercial

    @number_for_sale_commercial.setter
    def number_for_sale_commercial(self, number_for_sale_commercial):
        """Sets the number_for_sale_commercial of this DomainAgencyServiceV2ModelAgencyProfile.


        :param number_for_sale_commercial: The number_for_sale_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: int
        """

        self._number_for_sale_commercial = number_for_sale_commercial

    @property
    def number_for_rent_commercial(self):
        """Gets the number_for_rent_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The number_for_rent_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: int
        """
        return self._number_for_rent_commercial

    @number_for_rent_commercial.setter
    def number_for_rent_commercial(self, number_for_rent_commercial):
        """Sets the number_for_rent_commercial of this DomainAgencyServiceV2ModelAgencyProfile.


        :param number_for_rent_commercial: The number_for_rent_commercial of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: int
        """

        self._number_for_rent_commercial = number_for_rent_commercial

    @property
    def cre_agency_video_url(self):
        """Gets the cre_agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501


        :return: The cre_agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :rtype: str
        """
        return self._cre_agency_video_url

    @cre_agency_video_url.setter
    def cre_agency_video_url(self, cre_agency_video_url):
        """Sets the cre_agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.


        :param cre_agency_video_url: The cre_agency_video_url of this DomainAgencyServiceV2ModelAgencyProfile.  # noqa: E501
        :type: str
        """

        self._cre_agency_video_url = cre_agency_video_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainAgencyServiceV2ModelAgencyProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainAgencyServiceV2ModelAgencyProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
