# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainPublicAdapterWebApiModelsV1ListingsBusinessAd(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ad_type': 'str',
        'url': 'str'
    }

    attribute_map = {
        'ad_type': 'adType',
        'url': 'url'
    }

    def __init__(self, ad_type=None, url=None):  # noqa: E501
        """DomainPublicAdapterWebApiModelsV1ListingsBusinessAd - a model defined in Swagger"""  # noqa: E501

        self._ad_type = None
        self._url = None
        self.discriminator = None

        if ad_type is not None:
            self.ad_type = ad_type
        if url is not None:
            self.url = url

    @property
    def ad_type(self):
        """Gets the ad_type of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501

        Product type  # noqa: E501

        :return: The ad_type of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501
        :rtype: str
        """
        return self._ad_type

    @ad_type.setter
    def ad_type(self, ad_type):
        """Sets the ad_type of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.

        Product type  # noqa: E501

        :param ad_type: The ad_type of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501
        :type: str
        """

        self._ad_type = ad_type

    @property
    def url(self):
        """Gets the url of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501

        URL of property details page on CRE website  # noqa: E501

        :return: The url of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.

        URL of property details page on CRE website  # noqa: E501

        :param url: The url of this DomainPublicAdapterWebApiModelsV1ListingsBusinessAd.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainPublicAdapterWebApiModelsV1ListingsBusinessAd, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainPublicAdapterWebApiModelsV1ListingsBusinessAd):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
