# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'center': 'DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoPoint',
        'radius_in_meters': 'int'
    }

    attribute_map = {
        'center': 'center',
        'radius_in_meters': 'radiusInMeters'
    }

    def __init__(self, center=None, radius_in_meters=None):  # noqa: E501
        """DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle - a model defined in Swagger"""  # noqa: E501

        self._center = None
        self._radius_in_meters = None
        self.discriminator = None

        if center is not None:
            self.center = center
        if radius_in_meters is not None:
            self.radius_in_meters = radius_in_meters

    @property
    def center(self):
        """Gets the center of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501


        :return: The center of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501
        :rtype: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoPoint
        """
        return self._center

    @center.setter
    def center(self, center):
        """Sets the center of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.


        :param center: The center of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501
        :type: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoPoint
        """

        self._center = center

    @property
    def radius_in_meters(self):
        """Gets the radius_in_meters of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501


        :return: The radius_in_meters of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501
        :rtype: int
        """
        return self._radius_in_meters

    @radius_in_meters.setter
    def radius_in_meters(self, radius_in_meters):
        """Sets the radius_in_meters of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.


        :param radius_in_meters: The radius_in_meters of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle.  # noqa: E501
        :type: int
        """

        self._radius_in_meters = radius_in_meters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
