# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainSearchServiceV2ModelDomainSearchContractsV2Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'photo_url': 'str'
    }

    attribute_map = {
        'name': 'name',
        'photo_url': 'photoUrl'
    }

    def __init__(self, name=None, photo_url=None):  # noqa: E501
        """DomainSearchServiceV2ModelDomainSearchContractsV2Contact - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._photo_url = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if photo_url is not None:
            self.photo_url = photo_url

    @property
    def name(self):
        """Gets the name of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501


        :return: The name of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.


        :param name: The name of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def photo_url(self):
        """Gets the photo_url of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501


        :return: The photo_url of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501
        :rtype: str
        """
        return self._photo_url

    @photo_url.setter
    def photo_url(self, photo_url):
        """Sets the photo_url of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.


        :param photo_url: The photo_url of this DomainSearchServiceV2ModelDomainSearchContractsV2Contact.  # noqa: E501
        :type: str
        """

        self._photo_url = photo_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainSearchServiceV2ModelDomainSearchContractsV2Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainSearchServiceV2ModelDomainSearchContractsV2Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
