# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'year': 'int',
        'month': 'int',
        'values': 'dict(str, object)'
    }

    attribute_map = {
        'year': 'year',
        'month': 'month',
        'values': 'values'
    }

    def __init__(self, year=None, month=None, values=None):  # noqa: E501
        """DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel - a model defined in Swagger"""  # noqa: E501

        self._year = None
        self._month = None
        self._values = None
        self.discriminator = None

        if year is not None:
            self.year = year
        if month is not None:
            self.month = month
        if values is not None:
            self.values = values

    @property
    def year(self):
        """Gets the year of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501


        :return: The year of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.


        :param year: The year of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :type: int
        """

        self._year = year

    @property
    def month(self):
        """Gets the month of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501


        :return: The month of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :rtype: int
        """
        return self._month

    @month.setter
    def month(self, month):
        """Sets the month of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.


        :param month: The month of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :type: int
        """

        self._month = month

    @property
    def values(self):
        """Gets the values of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501


        :return: The values of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.


        :param values: The values of this DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel.  # noqa: E501
        :type: dict(str, object)
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SeriesInfoModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
