# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainNotificationPortalV1ModelAddSubscriptionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_type': 'str',
        'owner_type': 'str',
        'owner_id': 'str'
    }

    attribute_map = {
        'resource_type': 'resourceType',
        'owner_type': 'ownerType',
        'owner_id': 'ownerId'
    }

    def __init__(self, resource_type=None, owner_type=None, owner_id=None):  # noqa: E501
        """DomainNotificationPortalV1ModelAddSubscriptionRequest - a model defined in Swagger"""  # noqa: E501

        self._resource_type = None
        self._owner_type = None
        self._owner_id = None
        self.discriminator = None

        if resource_type is not None:
            self.resource_type = resource_type
        if owner_type is not None:
            self.owner_type = owner_type
        if owner_id is not None:
            self.owner_id = owner_id

    @property
    def resource_type(self):
        """Gets the resource_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501


        :return: The resource_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.


        :param resource_type: The resource_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def owner_type(self):
        """Gets the owner_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501


        :return: The owner_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :rtype: str
        """
        return self._owner_type

    @owner_type.setter
    def owner_type(self, owner_type):
        """Sets the owner_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.


        :param owner_type: The owner_type of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :type: str
        """

        self._owner_type = owner_type

    @property
    def owner_id(self):
        """Gets the owner_id of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501


        :return: The owner_id of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this DomainNotificationPortalV1ModelAddSubscriptionRequest.


        :param owner_id: The owner_id of this DomainNotificationPortalV1ModelAddSubscriptionRequest.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainNotificationPortalV1ModelAddSubscriptionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainNotificationPortalV1ModelAddSubscriptionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
