# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainListingAdminServiceV1ModelTender(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'recipient_name': 'str',
        'address': 'str',
        'end_date': 'datetime'
    }

    attribute_map = {
        'recipient_name': 'recipientName',
        'address': 'address',
        'end_date': 'endDate'
    }

    def __init__(self, recipient_name=None, address=None, end_date=None):  # noqa: E501
        """DomainListingAdminServiceV1ModelTender - a model defined in Swagger"""  # noqa: E501

        self._recipient_name = None
        self._address = None
        self._end_date = None
        self.discriminator = None

        if recipient_name is not None:
            self.recipient_name = recipient_name
        if address is not None:
            self.address = address
        if end_date is not None:
            self.end_date = end_date

    @property
    def recipient_name(self):
        """Gets the recipient_name of this DomainListingAdminServiceV1ModelTender.  # noqa: E501

        The recipient name of the tender, up to 50 characters  # noqa: E501

        :return: The recipient_name of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :rtype: str
        """
        return self._recipient_name

    @recipient_name.setter
    def recipient_name(self, recipient_name):
        """Sets the recipient_name of this DomainListingAdminServiceV1ModelTender.

        The recipient name of the tender, up to 50 characters  # noqa: E501

        :param recipient_name: The recipient_name of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :type: str
        """

        self._recipient_name = recipient_name

    @property
    def address(self):
        """Gets the address of this DomainListingAdminServiceV1ModelTender.  # noqa: E501

        Street address, up to 100 characters.  # noqa: E501

        :return: The address of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this DomainListingAdminServiceV1ModelTender.

        Street address, up to 100 characters.  # noqa: E501

        :param address: The address of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def end_date(self):
        """Gets the end_date of this DomainListingAdminServiceV1ModelTender.  # noqa: E501

        Closing Date  # noqa: E501

        :return: The end_date of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this DomainListingAdminServiceV1ModelTender.

        Closing Date  # noqa: E501

        :param end_date: The end_date of this DomainListingAdminServiceV1ModelTender.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainListingAdminServiceV1ModelTender, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainListingAdminServiceV1ModelTender):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
