# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainListingAdminServiceV1ModelAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_option': 'str',
        'state': 'str',
        'unit_number': 'str',
        'street': 'str',
        'suggested_geo_location': 'DomainListingAdminServiceV1ModelGeoLocation',
        'street_number': 'str',
        'suburb': 'str',
        'postcode': 'str'
    }

    attribute_map = {
        'display_option': 'displayOption',
        'state': 'state',
        'unit_number': 'unitNumber',
        'street': 'street',
        'suggested_geo_location': 'suggestedGeoLocation',
        'street_number': 'streetNumber',
        'suburb': 'suburb',
        'postcode': 'postcode'
    }

    def __init__(self, display_option=None, state=None, unit_number=None, street=None, suggested_geo_location=None, street_number=None, suburb=None, postcode=None):  # noqa: E501
        """DomainListingAdminServiceV1ModelAddress - a model defined in Swagger"""  # noqa: E501

        self._display_option = None
        self._state = None
        self._unit_number = None
        self._street = None
        self._suggested_geo_location = None
        self._street_number = None
        self._suburb = None
        self._postcode = None
        self.discriminator = None

        if display_option is not None:
            self.display_option = display_option
        if state is not None:
            self.state = state
        if unit_number is not None:
            self.unit_number = unit_number
        if street is not None:
            self.street = street
        if suggested_geo_location is not None:
            self.suggested_geo_location = suggested_geo_location
        if street_number is not None:
            self.street_number = street_number
        if suburb is not None:
            self.suburb = suburb
        if postcode is not None:
            self.postcode = postcode

    @property
    def display_option(self):
        """Gets the display_option of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        What granularity to display the properties location at  # noqa: E501

        :return: The display_option of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._display_option

    @display_option.setter
    def display_option(self, display_option):
        """Sets the display_option of this DomainListingAdminServiceV1ModelAddress.

        What granularity to display the properties location at  # noqa: E501

        :param display_option: The display_option of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """
        allowed_values = ["fullAddress", "streetAndSuburb", "suburbOnly", "regionOnly", "areaOnly", "stateOnly", "unspecified"]  # noqa: E501
        if display_option not in allowed_values:
            raise ValueError(
                "Invalid value for `display_option` ({0}), must be one of {1}"  # noqa: E501
                .format(display_option, allowed_values)
            )

        self._display_option = display_option

    @property
    def state(self):
        """Gets the state of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        State  # noqa: E501

        :return: The state of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this DomainListingAdminServiceV1ModelAddress.

        State  # noqa: E501

        :param state: The state of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """
        allowed_values = ["nsw", "vic", "act", "sa", "wa", "tas", "qld", "nt"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def unit_number(self):
        """Gets the unit_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Unit number for apartments, maximum 30 characters  # noqa: E501

        :return: The unit_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._unit_number

    @unit_number.setter
    def unit_number(self, unit_number):
        """Sets the unit_number of this DomainListingAdminServiceV1ModelAddress.

        Unit number for apartments, maximum 30 characters  # noqa: E501

        :param unit_number: The unit_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """

        self._unit_number = unit_number

    @property
    def street(self):
        """Gets the street of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Street name, maximum 100 characters  # noqa: E501

        :return: The street of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this DomainListingAdminServiceV1ModelAddress.

        Street name, maximum 100 characters  # noqa: E501

        :param street: The street of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """

        self._street = street

    @property
    def suggested_geo_location(self):
        """Gets the suggested_geo_location of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Provide the latitude and longitude for the property to show in the map  # noqa: E501

        :return: The suggested_geo_location of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: DomainListingAdminServiceV1ModelGeoLocation
        """
        return self._suggested_geo_location

    @suggested_geo_location.setter
    def suggested_geo_location(self, suggested_geo_location):
        """Sets the suggested_geo_location of this DomainListingAdminServiceV1ModelAddress.

        Provide the latitude and longitude for the property to show in the map  # noqa: E501

        :param suggested_geo_location: The suggested_geo_location of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: DomainListingAdminServiceV1ModelGeoLocation
        """

        self._suggested_geo_location = suggested_geo_location

    @property
    def street_number(self):
        """Gets the street_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Street number, maximum 20 characters  # noqa: E501

        :return: The street_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._street_number

    @street_number.setter
    def street_number(self, street_number):
        """Sets the street_number of this DomainListingAdminServiceV1ModelAddress.

        Street number, maximum 20 characters  # noqa: E501

        :param street_number: The street_number of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """

        self._street_number = street_number

    @property
    def suburb(self):
        """Gets the suburb of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Suburb name , maximum 50 characters  # noqa: E501

        :return: The suburb of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._suburb

    @suburb.setter
    def suburb(self, suburb):
        """Sets the suburb of this DomainListingAdminServiceV1ModelAddress.

        Suburb name , maximum 50 characters  # noqa: E501

        :param suburb: The suburb of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """

        self._suburb = suburb

    @property
    def postcode(self):
        """Gets the postcode of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501

        Postcode  # noqa: E501

        :return: The postcode of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._postcode

    @postcode.setter
    def postcode(self, postcode):
        """Sets the postcode of this DomainListingAdminServiceV1ModelAddress.

        Postcode  # noqa: E501

        :param postcode: The postcode of this DomainListingAdminServiceV1ModelAddress.  # noqa: E501
        :type: str
        """

        self._postcode = postcode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainListingAdminServiceV1ModelAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainListingAdminServiceV1ModelAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
