# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'box': 'DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsBox',
        'circle': 'DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle',
        'polygon': 'DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon'
    }

    attribute_map = {
        'box': 'box',
        'circle': 'circle',
        'polygon': 'polygon'
    }

    def __init__(self, box=None, circle=None, polygon=None):  # noqa: E501
        """DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow - a model defined in Swagger"""  # noqa: E501

        self._box = None
        self._circle = None
        self._polygon = None
        self.discriminator = None

        if box is not None:
            self.box = box
        if circle is not None:
            self.circle = circle
        if polygon is not None:
            self.polygon = polygon

    @property
    def box(self):
        """Gets the box of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501


        :return: The box of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :rtype: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsBox
        """
        return self._box

    @box.setter
    def box(self, box):
        """Sets the box of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.


        :param box: The box of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :type: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsBox
        """

        self._box = box

    @property
    def circle(self):
        """Gets the circle of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501


        :return: The circle of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :rtype: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle
        """
        return self._circle

    @circle.setter
    def circle(self, circle):
        """Sets the circle of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.


        :param circle: The circle of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :type: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCircle
        """

        self._circle = circle

    @property
    def polygon(self):
        """Gets the polygon of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501


        :return: The polygon of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :rtype: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
        """
        return self._polygon

    @polygon.setter
    def polygon(self, polygon):
        """Sets the polygon of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.


        :param polygon: The polygon of this DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow.  # noqa: E501
        :type: DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
        """

        self._polygon = polygon

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsGeoWindow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
