# coding: utf-8

"""
    Domain Group API V1

    Provides public access to Domain's microservices  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'carspaces': 'int'
    }

    attribute_map = {
        'type': 'type',
        'carspaces': 'carspaces'
    }

    def __init__(self, type=None, carspaces=None):  # noqa: E501
        """DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._carspaces = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if carspaces is not None:
            self.carspaces = carspaces

    @property
    def type(self):
        """Gets the type of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501

        Parking type  # noqa: E501

        :return: The type of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.

        Parking type  # noqa: E501

        :param type: The type of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501
        :type: str
        """
        allowed_values = ["onSite", "onStreet", "noParking"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def carspaces(self):
        """Gets the carspaces of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501

        Minimum carspace count  # noqa: E501

        :return: The carspaces of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501
        :rtype: int
        """
        return self._carspaces

    @carspaces.setter
    def carspaces(self, carspaces):
        """Sets the carspaces of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.

        Minimum carspace count  # noqa: E501

        :param carspaces: The carspaces of this DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch.  # noqa: E501
        :type: int
        """

        self._carspaces = carspaces

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainPublicAdapterWebApiModelsV1ListingsCommercialParkingSearch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
