name: Coverage

on: pull_request
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: pip install nox
      - name: Generate Coverage Report
        run: nox --sessions tests coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          CLIENT_ID: ${{ secrets.DOMAIN_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DOMAIN_CLIENT_SECRET }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
          WSAPIKEY: ${{ secrets.WSAPIKEY }}