name: Deploy Feature Branch

on:
  push:
    branches:
      - feature/configure_cicd

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        npm install
        sls plugin install -n serverless-python-requirements

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLIENT_ID: ${{ secrets.DOMAIN_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.DOMAIN_CLIENT_SECRET }}