name: Deploy Feature Branch

on:
  push:
    branches:
      - feature/configure_cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Serverless Deploy
        run: npm run-script deploy
        env:
          CLIENT_ID: ${{ secrets.DOMAIN_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DOMAIN_CLIENT_SECRET }}