name: Deploy Feature Branch

on:
  push:
    branches:
      - feature/configure_cicd

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install

    - name: serverless serverless-python-requirements install
      uses: spring-media/serverless-github-actions-playground/.github/workflows@ci_cd
      with:
        args: plugin install -n serverless-python-requirements
        
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLIENT_ID: ${{ secrets.DOMAIN_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.DOMAIN_CLIENT_SECRET }}