name: PR Comment Testing

on: pull_request
jobs:
  comment:
    name: Add checkout commands
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: pip install nox
      - run: nox
